;;;; Address Book — contacts with normalised-identifier deduplication and merge.

(defpackage #:address-book
  (:use #:cl)
  (:export #:make-contact #:make-address-book
           #:ab-add #:ab-get #:ab-find-duplicates #:ab-merge
           #:ab-search-by-name #:ab-search-by-email
           #:canonical-email #:canonical-phone
           #:contact-id #:contact-name #:contact-emails #:contact-phones
           #:contact-tags #:contact-address #:contact-notes #:contact-created-ms))

(in-package #:address-book)

(defstruct contact
  (id 0 :type integer)
  (name "" :type string)
  (emails nil :type list)
  (phones nil :type list)
  (tags nil :type list)
  (address "" :type string)
  (notes "" :type string)
  (created-ms 0 :type integer))

(defun ab-make-contact (id name created-ms &key emails phones tags (address "") (notes ""))
  (make-contact :id id :name name :created-ms created-ms
                :emails (or emails nil) :phones (or phones nil)
                :tags (or tags nil) :address address :notes notes))

(defun canonical-email (email)
  (let* ((trimmed (string-trim " " email))
         (lower (string-downcase trimmed))
         (at (position #\@ lower)))
    (if (null at)
        lower
        (let* ((local (subseq lower 0 at))
               (domain (subseq lower (1+ at)))
               (plus (position #\+ local)))
          (when plus (setf local (subseq local 0 plus)))
          (when (or (string= domain "gmail.com") (string= domain "googlemail.com"))
            (setf local (remove #\. local))
            (setf domain "gmail.com"))
          (format nil "~A@~A" local domain)))))

(defun canonical-phone (phone)
  (let* ((digits (with-output-to-string (out)
                   (loop for c across phone
                         when (digit-char-p c) do (write-char c out)))))
    (if (and (= (length digits) 11) (char= (char digits 0) #\1))
        (subseq digits 1)
        digits)))

(defun contact-canonical-emails (c)
  (mapcar #'canonical-email (contact-emails c)))

(defun contact-canonical-phones (c)
  (mapcar #'canonical-phone (contact-phones c)))

(defstruct address-book
  (contacts (make-hash-table) :type hash-table)
  (next-id 1 :type integer))

(defun ab-add (ab contact)
  (when (>= (contact-id contact) (address-book-next-id ab))
    (setf (address-book-next-id ab) (1+ (contact-id contact))))
  (setf (gethash (contact-id contact) (address-book-contacts ab)) contact)
  (contact-id contact))

(defun ab-new-id (ab)
  (let ((id (address-book-next-id ab)))
    (incf (address-book-next-id ab))
    id))

(defun ab-get (ab id)
  (gethash id (address-book-contacts ab)))

;; Union-find implementation.
(defun uf-find (parent x)
  (let ((p (gethash x parent)))
    (if (= p x) x
        (let ((root (uf-find parent p)))
          (setf (gethash x parent) root)
          root))))

(defun uf-union (parent a b)
  (let ((ra (uf-find parent a))
        (rb (uf-find parent b)))
    (unless (= ra rb)
      (setf (gethash ra parent) rb))))

(defun ab-find-duplicates (ab)
  (let ((by-email (make-hash-table :test 'equal))
        (by-phone (make-hash-table :test 'equal)))
    (maphash (lambda (id c)
               (dolist (e (contact-canonical-emails c))
                 (unless (zerop (length e))
                   (push id (gethash e by-email))))
               (dolist (p (contact-canonical-phones c))
                 (unless (zerop (length p))
                   (push id (gethash p by-phone)))))
             (address-book-contacts ab))
    (let ((parent (make-hash-table)))
      (maphash (lambda (id c) (declare (ignore c))
                 (setf (gethash id parent) id))
               (address-book-contacts ab))
      (dolist (h (list by-email by-phone))
        (maphash (lambda (k ids)
                   (declare (ignore k))
                   (let ((uniq (remove-duplicates ids)))
                     (loop for i from 1 below (length uniq)
                           do (uf-union parent (first uniq) (nth i uniq)))))
                 h))
      (let ((groups (make-hash-table)))
        (maphash (lambda (id c) (declare (ignore c))
                   (let ((root (uf-find parent id)))
                     (push id (gethash root groups))))
                 (address-book-contacts ab))
        (let ((out nil))
          (maphash (lambda (k g) (declare (ignore k))
                     (when (>= (length g) 2)
                       (push (sort (copy-list g) #'<) out)))
                   groups)
          (sort out (lambda (a b) (< (first a) (first b)))))))))

(defun longest-non-empty (strings)
  (let ((best nil)
        (best-len -1))
    (dolist (s strings)
      (when (and (> (length s) 0) (> (length s) best-len))
        (setf best s best-len (length s))))
    (or best "")))

(defun merge-sets (sources accessor)
  (let ((seen (make-hash-table :test 'equal))
        (out nil))
    (dolist (c sources)
      (dolist (v (funcall accessor c))
        (when (and (> (length v) 0) (not (gethash v seen)))
          (setf (gethash v seen) t)
          (push v out))))
    (sort out #'string<)))

(defun ab-merge (ab ids)
  (when (< (length ids) 2)
    (error "need at least 2 ids to merge"))
  (let ((sources nil))
    (dolist (id ids)
      (let ((c (ab-get ab id)))
        (unless c (error "id ~A not found" id))
        (push c sources)))
    (setf sources (nreverse sources))
    (let* ((merged-id (ab-new-id ab))
           (earliest (reduce #'min sources :key #'contact-created-ms))
           (longest (longest-non-empty (mapcar #'contact-name sources)))
           (emails (merge-sets sources #'contact-emails))
           (phones (merge-sets sources #'contact-phones))
           (tags (merge-sets sources #'contact-tags))
           (addrs (remove-if (lambda (s) (zerop (length s)))
                              (mapcar #'contact-address sources)))
           (notes (remove-if (lambda (s) (zerop (length s)))
                              (mapcar #'contact-notes sources)))
           (merged (make-contact :id merged-id :name longest
                                  :emails emails :phones phones :tags tags
                                  :address (format nil "~{~A~^ | ~}" addrs)
                                  :notes (format nil "~{~A~^~%---~%~}" notes)
                                  :created-ms earliest)))
      (dolist (id ids) (remhash id (address-book-contacts ab)))
      (setf (gethash merged-id (address-book-contacts ab)) merged)
      merged-id)))

(defun ab-search-by-name (ab needle)
  (let ((lc (string-downcase needle))
        (out nil))
    (maphash (lambda (id c)
               (when (search lc (string-downcase (contact-name c)))
                 (push id out)))
             (address-book-contacts ab))
    (sort out #'<)))

(defun ab-search-by-email (ab email)
  (let ((canonical (canonical-email email))
        (out nil))
    (maphash (lambda (id c)
               (when (find canonical (contact-canonical-emails c) :test #'string=)
                 (push id out)))
             (address-book-contacts ab))
    (sort out #'<)))

(defun demo ()
  (let ((ab (make-address-book)))
    (ab-add ab (ab-make-contact 1 "Alice" 100
                                  :emails '("alice@gmail.com")
                                  :phones '("555-1111")))
    (ab-add ab (ab-make-contact 2 "Alice J. Smith" 200
                                  :emails '("a.l.i.c.e@gmail.com" "alice.smith@example.com")
                                  :phones '("(555) 2222")))
    (ab-add ab (ab-make-contact 3 "Bob" 300
                                  :emails '("bob@gmail.com")
                                  :phones '("555-3333")))
    (format t "=== duplicates ===~%")
    (dolist (group (ab-find-duplicates ab))
      (let ((names (mapcar (lambda (id) (contact-name (ab-get ab id))) group)))
        (format t "  group ~A: ~A~%" group names)))
    (format t "~%=== merging 1 and 2 ===~%")
    (let* ((merged-id (ab-merge ab '(1 2)))
           (merged (ab-get ab merged-id)))
      (format t "  new id: ~D~%" merged-id)
      (format t "  name: ~A~%" (contact-name merged))
      (format t "  emails: ~A~%" (contact-emails merged))
      (format t "  phones: ~A~%" (contact-phones merged))
      (format t "  earliest created_ms: ~D~%" (contact-created-ms merged)))
    (format t "~%=== remaining contacts ===~%")
    (let ((ids nil))
      (maphash (lambda (id c) (declare (ignore c)) (push id ids))
               (address-book-contacts ab))
      (dolist (id (sort ids #'<))
        (format t "  ~D: ~A~%" id (contact-name (ab-get ab id)))))))
