;;;; Database Backup Script Maker — code generation with shell-safe quoting.

(defpackage #:backup-script-maker
  (:use #:cl)
  (:export #:make-backup-spec #:validate-spec #:shell-quote #:emit-script
           #:is-valid-identifier))

(in-package #:backup-script-maker)

(defstruct backup-spec
  (database "" :type string)
  (host "localhost" :type string)
  (port 5432 :type integer)
  (user "postgres" :type string)
  (tables-include nil :type list)
  (tables-exclude nil :type list)
  (destination-dir "/var/backups" :type string)
  (compress t :type boolean)
  (format :sql :type keyword))

(defun is-valid-identifier (s)
  (and (> (length s) 0)
       (let ((first (char s 0)))
         (and (or (alpha-char-p first) (char= first #\_))
              (loop for i from 1 below (length s)
                    for c = (char s i)
                    always (or (alphanumericp c) (char= c #\_)))))))

(defun validate-spec (spec)
  (let ((errors nil))
    (when (zerop (length (backup-spec-database spec)))
      (push '(:empty-database) errors))
    (when (zerop (length (backup-spec-destination-dir spec)))
      (push '(:empty-destination) errors))
    (when (zerop (backup-spec-port spec))
      (push '(:port-zero) errors))
    (unless (is-valid-identifier (backup-spec-database spec))
      (push (list :invalid-identifier (backup-spec-database spec)) errors))
    (dolist (t1 (append (backup-spec-tables-include spec)
                         (backup-spec-tables-exclude spec)))
      (unless (is-valid-identifier t1)
        (push (list :invalid-identifier t1) errors)))
    (nreverse errors)))

(defun escape-single-quote (s)
  (with-output-to-string (out)
    (loop for c across s do
          (cond ((char= c #\')
                 (write-string "'\\''" out))
                (t (write-char c out))))))

(defun shell-quote (s)
  (format nil "'~A'" (escape-single-quote s)))

(defun emit-sql-command (spec)
  (let ((cmd "pg_dump -h \"$HOST\" -p \"$PORT\" -U \"$USER\" \"$DB\""))
    (dolist (t1 (sort (copy-list (backup-spec-tables-exclude spec)) #'string<))
      (setf cmd (format nil "~A --exclude-table=~A" cmd (shell-quote t1))))
    (let ((includes (remove-if (lambda (t1)
                                  (member t1 (backup-spec-tables-exclude spec) :test #'string=))
                                (backup-spec-tables-include spec))))
      (dolist (t1 (sort (copy-list includes) #'string<))
        (setf cmd (format nil "~A --table=~A" cmd (shell-quote t1)))))
    cmd))

(defun emit-script (spec)
  (let ((errors (validate-spec spec)))
    (when errors (return-from emit-script errors)))
  (with-output-to-string (out)
    (format out "#!/usr/bin/env bash~%")
    (format out "set -euo pipefail~%~%")
    (format out "DB=~A~%" (shell-quote (backup-spec-database spec)))
    (format out "HOST=~A~%" (shell-quote (backup-spec-host spec)))
    (format out "PORT=~D~%" (backup-spec-port spec))
    (format out "USER=~A~%" (shell-quote (backup-spec-user spec)))
    (format out "DEST=~A~%" (shell-quote (backup-spec-destination-dir spec)))
    (format out "STAMP=$(date -u +%Y%m%dT%H%M%SZ)~%")
    (format out "mkdir -p \"$DEST\"~%~%")
    (case (backup-spec-format spec)
      (:sql
       (let ((cmd (emit-sql-command spec)))
         (write-string cmd out)
         (if (backup-spec-compress spec)
             (write-string " | gzip > \"$DEST/${DB}_${STAMP}.sql.gz\"" out)
             (write-string " > \"$DEST/${DB}_${STAMP}.sql\"" out))
         (terpri out)))
      (:csv-per-table
       (let ((tables (if (backup-spec-tables-include spec)
                          (sort (remove-if (lambda (t1)
                                              (member t1 (backup-spec-tables-exclude spec)
                                                       :test #'string=))
                                            (copy-list (backup-spec-tables-include spec)))
                                 #'string<)
                          (list "__introspect__"))))
         (dolist (t1 tables)
           (let* ((tq (if (string= t1 "__introspect__") t1 (shell-quote t1)))
                  (base (format nil "psql -h \"$HOST\" -p \"$PORT\" -U \"$USER\" -c \"\\\\copy ~A TO STDOUT WITH CSV HEADER\" \"$DB\"" tq)))
             (write-string base out)
             (if (backup-spec-compress spec)
                 (format out " | gzip > \"$DEST/${DB}_~A_${STAMP}.csv.gz\"~%" tq)
                 (format out " > \"$DEST/${DB}_~A_${STAMP}.csv\"~%" tq)))))))
    (format out "~%echo \"backup complete: $DEST\"~%")))

(defun demo ()
  (let ((spec (make-backup-spec :database "appdb"
                                  :tables-include '("users" "orders")
                                  :tables-exclude '("logs")
                                  :compress t)))
    (format t "~A" (emit-script spec))))
